M48
; DRILL file {KiCad 7.0.10} date 
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-20T15:40:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X34.0Y-67.0
X50.15Y-137.0
X61.0Y-96.0
X66.25Y-34.0
X84.0Y-67.0
X100.15Y-137.0
X111.0Y-96.0
X116.25Y-34.0
M30
