M48
; DRILL file {KiCad 8.0.5} date 2024-11-03T10:01:35+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-03T10:01:35+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.305
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T7C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T8C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T9C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T10C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T11C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T12C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T13C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T14C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T15C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T16C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T17C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T18C4.000
%
G90
G05
T1
X227.9Y-109.5
T2
X230.9Y-109.5
T3
X233.9Y-109.5
T4
X236.9Y-109.5
T5
X239.9Y-109.5
T6
X242.9Y-109.5
T7
X227.9Y-117.5
T8
X230.9Y-117.5
T9
X233.9Y-117.5
T10
X236.9Y-117.5
T11
X239.9Y-117.5
T12
X165.92Y-125.0
X176.08Y-125.0
X185.92Y-125.0
X196.08Y-125.0
T13
X242.9Y-117.5
T14
X227.9Y-126.5
T15
X231.9Y-126.5
T16
X54.0Y-54.0
X54.0Y-146.0
X246.0Y-54.0
X246.0Y-146.0
T17
X236.9Y-126.5
T18
X171.0Y-125.0
X191.0Y-125.0
X241.9Y-126.5
M30
