/* AUTO-GENERATED by tools/gen_sequences.py from sequences.md — DO NOT EDIT */

#ifndef __SEQUENCES_H
#define __SEQUENCES_H

#include <stdint.h>

/* phrase structure — single source of truth is gen_sequences.py */
#define SEQ_BARS_PER_PHRASE 4
#define SEQ_BEATS_PER_BAR 8
#define SEQ_SUBSTEPS_PER_BEAT 4 /* 4 PPQN clock input */
#define SEQ_BAR_STEPS (SEQ_BEATS_PER_BAR * SEQ_SUBSTEPS_PER_BEAT)
#define SEQ_PHRASE_STEPS (SEQ_BARS_PER_PHRASE * SEQ_BAR_STEPS)

#define SEQ_FLAG_GATE 0x01   /* note plays on this sub-step */
#define SEQ_FLAG_TIE 0x02    /* gate held, no retrigger (legato) */
#define SEQ_FLAG_ACCENT 0x04 /* reserved */

#define SEQ_STEP_REST (-1)

struct SEQ_step
{
    int8_t note;   /* semitone from 0V C, SEQ_STEP_REST when silent */
    uint8_t flags; /* SEQ_FLAG_* */
};

struct SEQ_sequence
{
    const char* name;
    uint16_t step_count;
    const struct SEQ_step* steps;
};

/* bank sizes are data, never hard-code them downstream */
extern const struct SEQ_sequence SEQ_bank_a[]; /* lead */
extern const uint16_t SEQ_bank_a_count;
extern const struct SEQ_sequence SEQ_bank_b[]; /* bass */
extern const uint16_t SEQ_bank_b_count;

#endif
